# Generated by Django 4.2.7 on 2023-11-02 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaNac', models.DateField(blank=True, null=True)),
                ('fechaDeceso', models.DateField(blank=True, null=True, verbose_name='Fallecido')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del género (por ej: PRogramación, DB, SO, etc.)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del idioma, por ej: Inglés, etc.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField(help_text='Ingrese un resumen del libro', max_length=1000)),
                ('isbn', models.CharField(help_text='13 caracteres <a href="https://www.isbn-international.org/content/what-isbn/10">ISBN numero</a>', max_length=13, verbose_name='ISBN')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='catalogo/upload/img')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.autor')),
                ('genero', models.ManyToManyField(help_text='Seleccione un genero (o varios) para el libro.', to='catalogo.genero')),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para este libro particular en toda la biblioteca', primary_key=True, serialize=False)),
                ('fechaDevolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('m', 'en mantenimiento'), ('p', 'prestado'), ('d', 'disponible'), ('r', 'reservado')], default='d', help_text='Disponibilidad del ejemplar', max_length=1)),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.libro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fechaDevolucion'],
            },
        ),
    ]
